### ISSUE TITLE
i need to keep my stub file

### ISSUE THREAD

**Issue by ajikamaludin-dev** [binafy/laravel-stub#6]
https://github.com/binafy/laravel-stub/blob/237587421b3f14b48806d1b98c44b968629d4f52/src/LaravelStub.php#L145

from this line of code im using local stub file for example my-projects/stubs/SampleController.stubs, when generate the original stubs file is moved , consider you to changes this line of code to be 

```php
        // Copy file
        File::copy($this->from, $path);
```

so it can keep my original stub to more reuseable

**Comment by milwad-dev** [comment]
Update your dependencies:

https://github.com/binafy/laravel-stub/releases/tag/v1.0.1
